name: Run logdiff on simple test data

on:
  push:
    branches:
      - main

jobs:
  run-tests-and-logdiff:
    runs-on: ubuntu-latest
 
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Run the tests
        run: |
          /bin/bash test.sh

      - name: Modify filesystem permissions
        run: |
          chmod a+w .

      - name: Run logdiff
        uses: APTA-Technologies/logdiff@v1
        with:
          tracefile: 1_training.txt.dat
          inifile: edsm.ini

      - name: ls
        run: |
          ls -lah

      - name: upload result
        uses: actions/upload-artifact@v3
        with:
          name: 'result'
          path: '1_training.txt.dat.ff.final.json'
