name: Run logdiff on simple test data

on:
  push:
    branches:
      - main

jobs:
  run-tests-and-logdiff:
    runs-on: ubuntu-latest
 
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Run the tests
        run: |
          /bin/bash test.sh
      - name: Run logdiff
        uses: APTA-Technologies/logdiff@v1
        with:
          logfile: 1_training.txt.dat
      - name: upload result
        uses: actions/upload-artifact@v3
        with:
          name: 'result'
          path: '1_training.txt.dat.ff.final.json'
